services:
  clash-verge-rev:
    container_name: clash-verge-rev
    image: gua12345/docker_clash_vnc:latest
    volumes:
      - /root/clash-verge-rev/clash:/config/.local/share/io.github.clash-verge-rev.clash-verge-rev
    ports:
      - "5901:5901"
      - "6081:6081"
      - "7897:7897"
      - "9097:9097"
    restart: always
